"$schema" = 'https://starship.rs/config-schema.json'

scan_timeout = 100

format = """
[](love)\
$os\
$username\
[](bg:gold fg:love)\
$directory\
[](bg:foam fg:gold)\
$git_branch\
$git_status\
[](bg:iris fg:foam)\
$nodejs\
$python\
$php\
$rust\
$golang\
[ ](fg:iris)\
$cmd_duration\
$line_break\
$character"""

palette = 'flexoki_dark'

[palettes.flexoki_dark]
surface = '#100F0F'
muted   = '#878580'
love    = '#D14D41'
gold    = '#D0A215'
foam    = '#3AA99F'
iris    = '#8B7EC8'

[palettes.flexoki_light]
base    = '#100F0F'
surface = '#FFFCF0'
overlay = '#F2F0E5'
muted   = '#878580'
subtle  = '#6F6E69'
text    = '#100F0F'

love    = '#AF3029'
gold    = '#AD8301'
rose    = '#A02F6F'
pine    = '#66800B'
foam    = '#24837B'
iris    = '#5E409D'
hl_med  = '#CECDC3'

[os]
disabled = false
style = "bg:love fg:surface"

[os.symbols]
Arch = " "

[username]
show_always = true
style_user = "bg:love fg:surface"
style_root = "bg:love fg:surface"
format = '[ $user ]($style)'

[directory]
style = "bg:gold fg:surface"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = " "
style = "bg:foam fg:surface"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:foam fg:surface"
format = '[$all_status$ahead_behind ]($style)'

[nodejs]
symbol = " "
style = "bg:iris fg:surface"
format = '[ $symbol($version) ]($style)'

[python]
symbol = " "
style = "bg:iris fg:surface"
format = '[ $symbol($version) ]($style)'

[php]
symbol = " "
style = "bg:iris fg:surface"
format = '[ $symbol($version) ]($style)'

[rust]
symbol = "󱘗 "
style = "bg:iris fg:surface"
format = '[ $symbol($version) ]($style)'

[golang]
symbol = " "
style = "bg:iris fg:surface"
format = '[ $symbol($version) ]($style)'

[cmd_duration]
min_time = 500
style = "fg:muted"
format = '[  $duration]($style)'

[character]
success_symbol = '[➜](bold fg:foam)'
error_symbol = '[➜](bold fg:love)'
